module GVars
  VERSION: String

  attr_accessor self.debug: bool?
  def self.debug?: () -> bool

  # Mixin methods
  def self?.global_variable_get: (interned name) -> untyped
  def self?.global_variable_set: [T] (interned name, T value) -> T
  def self?.alias_global_variable: (interned to_set, interned original) -> Symbol

  def self.global_variables: () -> Array[Symbol]

  alias self.get self.global_variable_get
  alias self.[] self.global_variable_get
  alias self.set self.global_variable_set
  alias self.[]= self.global_variable_set
  alias self.list self.global_variables
  alias self.alias self.alias_global_variable
end
