module GVars
  VERSION: String

  type getter[T] = ^(Symbol name) -> T
  type setter[T] = ^(Symbol name, T value) -> void

  # Top-level utility methods

  def self.get: (interned name) -> untyped
  def self.set: [T] (interned name, T value) -> T
  def self.list: () -> Array[Symbol]
  def self.alias: (interned to_set, interned original) -> Symbol
  alias self.[] self.get
  alias self.[]= self.set

  def self.readonly: (interned name) -> Symbol # raises error if unset
                   | (interned name, untyped value) -> Symbol
                   | (interned name) { (Symbol name) -> untyped } -> Symbol # same as `virtual` with a block

  def self.virtual: (interned name, getter[untyped] getter, ?setter[untyped]? setter) -> Symbol
                  | (interned name) { (Symbol name) -> untyped } -> Symbol # no setter

  def self.hooked: [T] (interned name, T initial) { (Symbol name, T old) -> T } -> Symbol # no setter allowed
                 | [T] (interned name, T initial, getter[T] getter, ?setter[T]? setter) -> Symbol

  # Mixin methods
  def global_variable_get: (interned name) -> untyped
  def global_variable_set: [T] (interned name, T value) -> T
  def alias_global_variable: (interned to_set, interned original) -> Symbol
end
